# Generated by Django 4.2.1 on 2023-05-08 17:26

import core.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address1',
            field=models.CharField(default='TEMP', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='address2',
            field=models.CharField(default='TEMP', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='care_preference',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('FOSTERING', 'Fostering'), ('ADOPTING', 'Adopting')], max_length=100), default=['Adopting', 'Fostering'], size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='TEMP', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='TEMP', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='TEMP', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_cat_age',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(validators=[core.models.validate_age]), blank=True, default=None, null=True, size=2),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_cat_breeds',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('AMERICAN_SHORTHAIR', 'American Shorthair'), ('PERSIAN', 'Persian'), ('SIAMESE', 'Siamese'), ('BRITISH_SHORTHAIR', 'British Shorthair'), ('BENGAL', 'Bengal'), ('MAINE_COON', 'Maine Coon'), ('SCOTTISH_FOLD', 'Scottish Fold'), ('SPHYNX', 'Sphynx'), ('RAGDOLL', 'Ragdoll'), ('MANX', 'Manx'), ('HIMALAYAN', 'Himalayan'), ('BIRMAN', 'Birman'), ('ABYSSINIAN', 'Abyssinian'), ('DEVON_REX', 'Devon Rex'), ('NORWEGIAN_FOREST_CAT', 'Norwegian Forest Cat'), ('EXOTIC_SHORTHAIR', 'Exotic Shorthair'), ('BALINESE', 'Balinese'), ('PETERBALD', 'Peterbald'), ('CORNISH_REX', 'Cornish Rex'), ('JAPANESE_BOBTAIL', 'Japanese Bobtail'), ('TURKISH_ANGORA', 'Turkish Angora'), ('TONKINESE', 'Tonkinese'), ('AMERICAN_BOBTAIL', 'American Bobtail'), ('ORIENTAL_SHORTHAIR', 'Oriental Shorthair'), ('SAVANNAH_CAT', 'Savannah Cat'), ('SCOTTISH_STRAIGHT', 'Scottish Straight'), ('AMERICAN_WIREHAIR', 'American Wirehair'), ('BRITISH_LONGHAIR', 'British Longhair'), ('CYMRIC', 'Cymric'), ('EGYPTIAN_MAU', 'Egyptian Mau'), ('KORAT', 'Korat'), ('LAPOERM', 'LaPerm'), ('OCICAT', 'Ocicat'), ('PIXIE_BOB', 'Pixie-Bob'), ('SNOWSHOE', 'Snowshoe'), ('SOMALI', 'Somali'), ('SPHYNX_CAT', 'Sphynx Cat'), ('THAI_CAT', 'Thai Cat'), ('TURKISH_VAN', 'Turkish Van')], max_length=100), blank=True, default=None, null=True, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_cat_characteristics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('SHORT_HAIRED', 'Short-haired'), ('LONG_HAIRED', 'Long-haired'), ('DOUBLE_COATED', 'Double-coated'), ('SINGLE_COATED', 'Single-coated'), ('CURLY', 'Curly'), ('STRAIGHT', 'Straight'), ('BLACK', 'Black'), ('WHITE', 'White'), ('GREY', 'Grey'), ('BROWN', 'Brown'), ('ORANGE', 'Orange'), ('CALICO', 'Calico'), ('TORTOISESHELL', 'Tortoiseshell'), ('TABBY', 'Tabby'), ('SIAMESE', 'Siamese'), ('PERSIAN', 'Persian'), ('BENGAL', 'Bengal'), ('RAGDOLL', 'Ragdoll'), ('SPHYNX', 'Sphynx'), ('FRIENDLY', 'Friendly'), ('AFFECTIONATE', 'Affectionate'), ('PLAYFUL', 'Playful'), ('INDEPENDENT', 'Independent'), ('LAID_BACK', 'Laid-back'), ('CURIOUS', 'Curious'), ('GENTLE', 'Gentle'), ('SHY', 'Shy'), ('RESERVED', 'Reserved'), ('VOCAL', 'Vocal'), ('ACTIVE', 'Active'), ('DOCILE', 'Docile'), ('ADAPTABLE', 'Adaptable'), ('ATTENTIVE', 'Attentive'), ('EASY_GOING', 'Easy-going'), ('PET_FRIENDLY', 'Pet Friendly')], max_length=100), blank=True, default=None, null=True, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_cat_temperaments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('FRIENDLY', 'Friendly'), ('AFFECTIONATE', 'Affectionate'), ('PLAYFUL', 'Playful'), ('INDEPENDENT', 'Independent'), ('LAID_BACK', 'Laid-back'), ('GENTLE', 'Gentle'), ('SHY', 'Shy'), ('RESERVED', 'Reserved'), ('VOCAL', 'Vocal'), ('ACTIVE', 'Active'), ('DOCILE', 'Docile'), ('ADAPTABLE', 'Adaptable'), ('ATTENTIVE', 'Attentive'), ('EASY_GOING', 'Easy-going'), ('STUBBORN', 'Stubborn'), ('AGGRESSIVE', 'Aggressive'), ('ANXIOUS', 'Anxious'), ('BRAVE', 'Brave'), ('CALM', 'Calm'), ('CONFIDENT', 'Confident'), ('COURAGEOUS', 'Courageous'), ('CURIOUS', 'Curious'), ('DEPENDABLE', 'Dependable'), ('DEVOTED', 'Devoted'), ('EAGER', 'Eager'), ('ENERGETIC', 'Energetic'), ('FAITHFUL', 'Faithful'), ('FEARLESS', 'Fearless'), ('FIERCE', 'Fierce'), ('GREGARIOUS', 'Gregarious'), ('HAPPY', 'Happy'), ('HARDWORKING', 'Hardworking'), ('HYPER', 'Hyper'), ('INTELLIGENT', 'Intelligent'), ('JOYFUL', 'Joyful'), ('KIND', 'Kind'), ('LIVELY', 'Lively'), ('LOYAL', 'Loyal'), ('MISCHIEVOUS', 'Mischievous'), ('NOBLE', 'Noble'), ('OBEDIENT', 'Obedient'), ('PATIENT', 'Patient'), ('PROTECTIVE', 'Protective'), ('QUICK', 'Quick'), ('QUIET', 'Quiet'), ('RELAXED', 'Relaxed'), ('RESPONSIBLE', 'Responsible'), ('SENSITIVE', 'Sensitive'), ('SENSIBLE', 'Sensible'), ('SERIOUS', 'Serious'), ('SINCERE', 'Sincere'), ('SOCIAL', 'Social'), ('STOIC', 'Stoic'), ('STRONG', 'Strong'), ('SWEET', 'Sweet'), ('TENACIOUS', 'Tenacious'), ('TERRITORIAL', 'Territorial'), ('TOUGH', 'Tough'), ('TRAINABLE', 'Trainable'), ('TRUSTWORTHY', 'Trustworthy'), ('VALIANT', 'Valiant'), ('VERSATILE', 'Versatile'), ('VIGILANT', 'Vigilant'), ('ZEALOUS', 'Zealous')], max_length=100), blank=True, default=None, null=True, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_dog_age',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(validators=[core.models.validate_age]), blank=True, default=None, null=True, size=2),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_dog_breeds',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('LABRADOR_RETRIEVER', 'Labrador Retriever'), ('GERMAN_SHEPHERD', 'German Shepherd'), ('GOLDEN_RETRIEVER', 'Golden Retriever'), ('FRENCH_BULLDOG', 'French Bulldog'), ('BEAGLE', 'Beagle'), ('BULLDOG', 'Bulldog'), ('POODLE', 'Poodle'), ('ROTTWEILER', 'Rottweiler'), ('YORKSHIRE_TERRIER', 'Yorkshire Terrier'), ('BOXER', 'Boxer'), ('SIBERIAN_HUSKY', 'Siberian Husky'), ('DACHSHUND', 'Dachshund'), ('SHIH_TZU', 'Shih Tzu'), ('GREAT_DANE', 'Great Dane'), ('CHIHUAHUA', 'Chihuahua'), ('BOSTON_TERRIER', 'Boston Terrier'), ('POMERANIAN', 'Pomeranian'), ('DOBERMAN_PINSCHER', 'Doberman Pinscher'), ('SHETLAND_SHEEPDOG', 'Shetland Sheepdog'), ('BICHON_FRISE', 'Bichon Frise'), ('BORDER_COLLIE', 'Border Collie'), ('PITBULL', 'Pitbull'), ('CAVALIER_KING_CHARLES_SPANIEL', 'Cavalier King Charles Spaniel'), ('AUSTRALIAN_SHEPHERD', 'Australian Shepherd'), ('SHAR_PEI', 'Shar Pei'), ('JACK_RUSSELL_TERRIER', 'Jack Russell Terrier'), ('ALASKAN_MALAMUTE', 'Alaskan Malamute'), ('BLOODHOUND', 'Bloodhound'), ('WEST_HIGHLAND_WHITE_TERRIER', 'West Highland White Terrier'), ('BASSET_HOUND', 'Basset Hound'), ('STAFFORDSHIRE_BULL_TERRIER', 'Staffordshire Bull Terrier'), ('WEIMARANER', 'Weimaraner'), ('SHIBA_INU', 'Shiba Inu'), ('BORZOI', 'Borzoi'), ('WHIPPET', 'Whippet'), ('MALTESE', 'Maltese'), ('AKITA', 'Akita'), ('CAVOODLE', 'Cavoodle'), ('CHOW_CHOW', 'Chow Chow'), ('PUG', 'Pug'), ('PAPILLON', 'Papillon'), ('SAMOYED', 'Samoyed'), ('LHASA_APSO', 'Lhasa Apso'), ('GREYHOUND', 'Greyhound'), ('OLD_ENGLISH_SHEEPDOG', 'Old English Sheepdog'), ('IRISH_SETTER', 'Irish Setter'), ('NEWFOUNDLAND', 'Newfoundland'), ('MINIATURE_SCHNAUZER', 'Miniature Schnauzer'), ('AFGHAN_HOUND', 'Afghan Hound'), ('CHINESE_CRESTED', 'Chinese Crested'), ('IRISH_WOLFHOUND', 'Irish Wolfhound')], max_length=100), blank=True, default=None, null=True, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_dog_characteristics',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large'), ('GIANT', 'Giant'), ('SHORT_HAIRED', 'Short-haired'), ('LONG_HAIRED', 'Long-haired'), ('DOUBLE_COATED', 'Double-coated'), ('SINGLE_COATED', 'Single-coated'), ('CURLY', 'Curly'), ('STRAIGHT', 'Straight'), ('WIRE_HAIRED', 'Wire-haired'), ('SMOOTH', 'Smooth'), ('BLACK', 'Black'), ('WHITE', 'White'), ('BROWN', 'Brown'), ('GOLDEN', 'Golden'), ('BRINDLE', 'Brindle'), ('SPOTTED', 'Spotted'), ('STRIPED', 'Striped'), ('SOLID', 'Solid'), ('PIED', 'Pied'), ('BLUE_EYES', 'Blue eyes'), ('BROWN_EYES', 'Brown eyes'), ('HAZEL_EYES', 'Hazel eyes'), ('GREEN_EYES', 'Green eyes'), ('BLACK_EYES', 'Black eyes')], max_length=100), blank=True, default=None, null=True, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_dog_temperaments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('FRIENDLY', 'Friendly'), ('AFFECTIONATE', 'Affectionate'), ('PLAYFUL', 'Playful'), ('INDEPENDENT', 'Independent'), ('LAID_BACK', 'Laid-back'), ('GENTLE', 'Gentle'), ('SHY', 'Shy'), ('RESERVED', 'Reserved'), ('VOCAL', 'Vocal'), ('ACTIVE', 'Active'), ('DOCILE', 'Docile'), ('ADAPTABLE', 'Adaptable'), ('ATTENTIVE', 'Attentive'), ('EASY_GOING', 'Easy-going'), ('STUBBORN', 'Stubborn'), ('AGGRESSIVE', 'Aggressive'), ('ANXIOUS', 'Anxious'), ('BRAVE', 'Brave'), ('CALM', 'Calm'), ('CONFIDENT', 'Confident'), ('COURAGEOUS', 'Courageous'), ('CURIOUS', 'Curious'), ('DEPENDABLE', 'Dependable'), ('DEVOTED', 'Devoted'), ('EAGER', 'Eager'), ('ENERGETIC', 'Energetic'), ('FAITHFUL', 'Faithful'), ('FEARLESS', 'Fearless'), ('FIERCE', 'Fierce'), ('GREGARIOUS', 'Gregarious'), ('HAPPY', 'Happy'), ('HARDWORKING', 'Hardworking'), ('HYPER', 'Hyper'), ('INTELLIGENT', 'Intelligent'), ('JOYFUL', 'Joyful'), ('KIND', 'Kind'), ('LIVELY', 'Lively'), ('LOYAL', 'Loyal'), ('MISCHIEVOUS', 'Mischievous'), ('NOBLE', 'Noble'), ('OBEDIENT', 'Obedient'), ('PATIENT', 'Patient'), ('PROTECTIVE', 'Protective'), ('QUICK', 'Quick'), ('QUIET', 'Quiet'), ('RELAXED', 'Relaxed'), ('RESPONSIBLE', 'Responsible'), ('SENSITIVE', 'Sensitive'), ('SENSIBLE', 'Sensible'), ('SERIOUS', 'Serious'), ('SINCERE', 'Sincere'), ('SOCIAL', 'Social'), ('STOIC', 'Stoic'), ('STRONG', 'Strong'), ('SWEET', 'Sweet'), ('TENACIOUS', 'Tenacious'), ('TERRITORIAL', 'Territorial'), ('TOUGH', 'Tough'), ('TRAINABLE', 'Trainable'), ('TRUSTWORTHY', 'Trustworthy'), ('VALIANT', 'Valiant'), ('VERSATILE', 'Versatile'), ('VIGILANT', 'Vigilant'), ('ZEALOUS', 'Zealous')], max_length=100), blank=True, default=None, null=True, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_species',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat')], max_length=100), default=['Dog', 'Cat'], size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=models.CharField(default='TEMP', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Organization Employee', 'ORGANIZATION_EMPLOYEE'), ('Adopter/Fosterer', 'ADOPTER_FOSTER'), ('Guardian', 'GUARDIAN')], default='Adopter/Fosterer', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='zip',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='TEMP', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='TEMP', max_length=255),
        ),
    ]
