# Generated by Django 4.2.1 on 2023-05-22 19:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_dog_user_created_at_user_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='care_preference',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('FOSTERING', 'Fostering'), ('ADOPTING', 'Adopting')], max_length=100), size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_species',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat')], max_length=100), size=None),
        ),
    ]
