from enum import Enum

class UserTypes(Enum):
    ORGANIZATION_EMPLOYEE = 'Organization Employee'
    ADOPTER_FOSTER = 'Adopter/Fosterer'
    GUARDIAN = 'Guardian'

class CarePreferences(Enum):
    FOSTERING = 'Fostering'
    ADOPTING = 'Adopting'

class PetSpecies(Enum):
    DOG = 'Dog'
    CAT = 'Cat'

class PetGender(Enum):
    MALE = 'Male'
    FEMALE = 'Female'

class PetSizes(Enum):
    SMALL = 'small'
    MEDIUM = 'medium'
    LARGE = 'large'
    EXTRA_LARGE = 'xlarge'

class PetStatuses(Enum):
    ADOPTABLE = 'adoptable'
    ADOPTED = 'adopted'
    FOSTERABLE = 'fosterable'
    FOSTERED = 'fostered'

class DogCoats(Enum):
    SHORT = "Short"
    MEDIUM = "Medium"
    LONG = "Long"
    WIRE = "Wire"
    CURLY = "Curly"
    HAIRLESS = "Hairless"
            
class DogColors(Enum):
    APRICOT = "Apricot / Beige"
    BICOLOR = "Bicolor"
    BLACK = "Black"
    BRINDLE = "Brindle"
    BROWN = "Brown / Chocolate"
    GOLDEN = "Golden"
    GRAY = "Gray / Blue / Silver"
    HARLEQUIN = "Harlequin"
    MERLE_BLUE = "Merle (Blue)"
    MERLE_RED = "Merle (Red)"
    RED = "Red / Chestnut / Orange"
    SABLE = "Sable"
    TRICOLOR = "Tricolor (Brown Black & White)"
    WHITE = "White / Cream"
    YELLOW = "Yellow / Tan / Blond / Fawn"

class DogBreeds(Enum):
    AFFENPINSCHER = "Affenpinscher"
    AFGHAN_HOUND = "Afghan Hound"
    AIREDALE_TERRIER = "Airedale Terrier"
    AKBASH = "Akbash"
    AKITA = "Akita"
    ALASKAN_MALAMUTE = "Alaskan Malamute"
    AMERICAN_BULLDOG = "American Bulldog"
    AMERICAN_BULLY = "American Bully"
    AMERICAN_ESKIMO_DOG = "American Eskimo Dog"
    AMERICAN_FOXHOUND = "American Foxhound"
    AMERICAN_HAIRLESS_TERRIER = "American Hairless Terrier"
    AMERICAN_STAFFORDSHIRE_TERRIER = "American Staffordshire Terrier"
    AMERICAN_WATER_SPANIEL = "American Water Spaniel"
    ANATOLIAN_SHEPHERD = "Anatolian Shepherd"
    APPENZELL_MOUNTAIN_DOG = "Appenzell Mountain Dog"
    AUSSEDOODLE = "Aussiedoodle"
    AUSTRALIAN_CATTLE_DOG_BLUE_HEELER = "Australian Cattle Dog / Blue Heeler"
    AUSTRALIAN_KELPIE = "Australian Kelpie"
    AUSTRALIAN_SHEPHERD = "Australian Shepherd"
    AUSTRALIAN_TERRIER = "Australian Terrier"
    BASENJI = "Basenji"
    BASSET_HOUND = "Basset Hound"
    BEAGLE = "Beagle"
    BEARDED_COLLIE = "Bearded Collie"
    BEAUCERON = "Beauceron"
    BEDLINGTON_TERRIER = "Bedlington Terrier"
    BELGIAN_SHEPHERD_LAEKENOIS = "Belgian Shepherd / Laekenois"
    BELGIAN_SHEPHERD_MALINOIS = "Belgian Shepherd / Malinois"
    BELGIAN_SHEPHERD_SHEEPDOG = "Belgian Shepherd / Sheepdog"
    BELGIAN_SHEPHERD_TERVUREN = "Belgian Shepherd / Tervuren"
    BERNESE_MOUNTAIN_DOG = "Bernese Mountain Dog"
    BICHON_FRISE = "Bichon Frise"
    BLACK_AND_TAN_COONHOUND = "Black and Tan Coonhound"
    BLACK_LABRADOR_RETRIEVER = "Black Labrador Retriever"
    BLACK_MOUTH_CUR = "Black Mouth Cur"
    BLACK_RUSSIAN_TERRIER = "Black Russian Terrier"
    BLOODHOUND = "Bloodhound"
    BLUE_LACY = "Blue Lacy"
    BLUETICK_COONHOUND = "Bluetick Coonhound"
    BOERBOEL = "Boerboel"
    BOLOGNESE = "Bolognese"
    BORDER_COLLIE = "Border Collie"
    BORDER_TERRIER = "Border Terrier"
    BORZOI = "Borzoi"
    BOSTON_TERRIER = "Boston Terrier"
    BOUVIER_DES_FLANDRES = "Bouvier des Flandres"
    BOXER = "Boxer"
    BOYKIN_SPANIEL = "Boykin Spaniel"
    BRIARD = "Briard"
    BRITTANY_SPANIEL = "Brittany Spaniel"
    BRUSSELS_GRIFFON = "Brussels Griffon"
    BULL_TERRIER = "Bull Terrier"
    BULLMASTIFF = "Bullmastiff"
    CAIRN_TERRIER = "Cairn Terrier"
    CANAAN_DOG = "Canaan Dog"
    CANE_CORSO = "Cane Corso"
    CARDIGAN_WELSH_CORGI = "Cardigan Welsh Corgi"
    CAROLINA_DOG = "Carolina Dog"
    CATAHOULA_LEOPARD_DOG = "Catahoula Leopard Dog"
    CATTLE_DOG = "Cattle Dog"
    CAUCASIAN_SHEEPDOG_CAUCASIAN_OVTCHARKA = "Caucasian Sheepdog / Caucasian Ovtcharka"
    CAVACHON = "Cavachon"
    CAVALIER_KING_CHARLES_SPANIEL = "Cavalier King Charles Spaniel"
    CAVAPOO = "Cavapoo"
    CHESAPEAKE_BAY_RETRIEVER = "Chesapeake Bay Retriever"
    CHIHUAHUA = "Chihuahua"
    CHINESE_CRESTED_DOG = "Chinese Crested Dog"
    CHINESE_FOO_DOG = "Chinese Foo Dog"
    CHINOOK = "Chinook"
    CHIWENIE = "Chiweenie"
    CHOCOLATE_LABRADOR_RETRIEVER = "Chocolate Labrador Retriever"
    CHOW_CHOW = "Chow Chow"
    CIRNECO_DELLETNAN = "Cirneco dell'Etna"
    CLUMBER_SPANIEL = "Clumber Spaniel"
    COCKAPOO = "Cockapoo"
    COCKER_SPANIEL = "Cocker Spaniel"
    COLLIE = "Collie"
    COONHOUND = "Coonhound"
    CORGI = "Corgi"
    COTON_DE_TULEAR = "Coton de Tulear"
    CURLY_COATED_RETRIEVER = "Curly-Coated Retriever"
    DACHSHUND = "Dachshund"
    DALMATIAN = "Dalmatian"
    DANDIE_DINMONT_TERRIER = "Dandie Dinmont Terrier"
    DOBERMAN_PINSCHER = "Doberman Pinscher"
    DOGO_ARGENTINO = "Dogo Argentino"
    DOGUE_DE_BORDEAUX = "Dogue de Bordeaux"
    DUTCH_SHEPHERD = "Dutch Shepherd"
    ENGLISH_BULLDOG = "English Bulldog"
    ENGLISH_COCKER_SPANIEL = "English Cocker Spaniel"
    ENGLISH_COONHOUND = "English Coonhound"
    ENGLISH_FOXHOUND = "English Foxhound"
    ENGLISH_POINTER = "English Pointer"
    ENGLISH_SETTER = "English Setter"
    ENGLISH_SHEPHERD = "English Shepherd"
    ENGLISH_SPRINGER_SPANIEL = "English Springer Spaniel"
    ENGLISH_TOY_SPANIEL = "English Toy Spaniel"
    ENTLEBUCHER = "Entlebucher"
    ESKIMO_DOG = "Eskimo Dog"
    FEIST = "Feist"
    FIELD_SPANIEL = "Field Spaniel"
    FILA_BRASILEIRO = "Fila Brasileiro"
    FINNISH_LAPPHUND = "Finnish Lapphund"
    FINNISH_SPITZ = "Finnish Spitz"
    FLAT_COATED_RETRIEVER = "Flat-Coated Retriever"
    FOX_TERRIER = "Fox Terrier"
    FOXHOUND = "Foxhound"
    FRENCH_BULLDOG = "French Bulldog"
    GALGO_SPANISH_GREYHOUND = "Galgo Spanish Greyhound"
    GERMAN_PINSCHER = "German Pinscher"
    GERMAN_SHEPHERD_DOG = "German Shepherd Dog"
    GERMAN_SHORTHAIRED_POINTER = "German Shorthaired Pointer"
    GERMAN_SPITZ = "German Spitz"
    GERMAN_WIREHAIRED_POINTER = "German Wirehaired Pointer"
    GIANT_SCHNAUZER = "Giant Schnauzer"
    GLEN_OF_IMAAL_TERRIER = "Glen of Imaal Terrier"
    GOLDEN_RETRIEVER = "Golden Retriever"
    GOLDENDOODLE = "Goldendoodle"
    GORDON_SETTER = "Gordon Setter"
    GREAT_DANE = "Great Dane"
    GREAT_PYRENEES = "Great Pyrenees"
    GREATER_SWISS_MOUNTAIN_DOG = "Greater Swiss Mountain Dog"
    GREYHOUND = "Greyhound"
    HAMILTONSTOVARE = "Hamiltonstovare"
    HARRIER = "Harrier"
    HAVANESE = "Havanese"
    HOUND = "Hound"
    HOVAWART = "Hovawart"
    HUSKY = "Husky"
    IBIAN_HOUND = "Ibizan Hound"
    ICELANDIC_SHEEPDOG = "Icelandic Sheepdog"
    ILLYRIAN_SHEEPDOG = "Illyrian Sheepdog"
    IRISH_SETTER = "Irish Setter"
    IRISH_TERRIER = "Irish Terrier"
    IRISH_WATER_SPANIEL = "Irish Water Spaniel"
    IRISH_WOLFHOUND = "Irish Wolfhound"
    ITALIAN_GREYHOUND = "Italian Greyhound"
    JACK_RUSSELL_TERRIER = "Jack Russell Terrier"
    JAPANESE_CHIN = "Japanese Chin"
    JINDO = "Jindo"
    KAI_DOG = "Kai Dog"
    KARELIAN_BEAR_DOG = "Karelian Bear Dog"
    KEESHOND = "Keeshond"
    KERRY_BLUE_TERRIER = "Kerry Blue Terrier"
    KISHU = "Kishu"
    KLEE_KAI = "Klee Kai"
    KOMONDOR = "Komondor"
    KUVASZ = "Kuvasz"
    KYI_LEO = "Kyi Leo"
    LABRADOODLE = "Labradoodle"
    LABRADOR_RETRIEVER = "Labrador Retriever"
    LAKELAND_TERRIER = "Lakeland Terrier"
    LANCASHIRE_HEELER = "Lancashire Heeler"
    LEONBERGER = "Leonberger"
    LHASA_APSO = "Lhasa Apso"
    LOWCHEN = "Lowchen"
    LURCHER = "Lurcher"
    MALTESE = "Maltese"
    MALTIPOO = "Maltipoo"
    MANCHESTER_TERRIER = "Manchester Terrier"
    MAREMMA_SHEEPDOG = "Maremma Sheepdog"
    MASTIFF = "Mastiff"
    MCNAB = "McNab"
    MINIATURE_BULL_TERRIER = "Miniature Bull Terrier"
    MINIATURE_PINSCHER = "Miniature Pinscher"
    MINIATURE_SCHNAUZER = "Miniature Schnauzer"
    MOUNTAIN_CUR = "Mountain Cur"
    MUNSTERLANDER = "Munsterlander"
    NEAPOLITAN_MASTIFF = "Neapolitan Mastiff"
    NEWFOUNDLAND = "Newfoundland"
    NORFOLK_TERRIER = "Norfolk Terrier"
    NORWEGIAN_BUHUND = "Norwegian Buhund"
    NORWEGIAN_ELKHOUND = "Norwegian Elkhound"
    NORWEGIAN_LUNDEHUND = "Norwegian Lundehund"
    NORWICH_TERRIER = "Norwich Terrier"
    NOVA_SCOTIA_DUCK_TOLLING_RETRIEVER = "Nova Scotia Duck Tolling Retriever"
    OLD_ENGLISH_BULLDOG = "Old English Bulldog"
    OLD_ENGLISH_SHEEPDOG = "Old English Sheepdog"
    OTTERHOUND = "Otterhound"
    PAPILLON = "Papillon"
    PEEK_A_POO = "Peekapoo"
    PEMBROKE_WELSH_CORGI = "Pembroke Welsh Corgi"
    PERUVIAN_INCA_ORCHID = "Peruvian Inca Orchid"
    PETIT_BASSET_GRIFFON_VENDEEN = "Petit Basset Griffon Vendeen"
    PHARAOH_HOUND = "Pharaoh Hound"
    PIT_BULL_TERIER = "Pit Bull Terrier"
    PITTIEPOO = "Pittiepoo"
    PLAB = "Plab"
    PLUMBER = "Plumber"
    POINTER = "Pointer"
    POLISH_LOWLAND_SHEEPDOG = "Polish Lowland Sheepdog"
    POMERANIAN = "Pomeranian"
    POMSKY = "Pomsky"
    POODLE = "Poodle"
    PORTUGUESE_WATER_DOG = "Portuguese Water Dog"
    PRESA_CANARIO = "Presa Canario"
    PRESA_MALLORQUIN = "Presa Mallorquin"
    PUG = "Pug"
    PULI = "Puli"
    PUMI = "Pumi"
    QUEENSLAND_HEELER = "Queensland Heeler"
    RAT_TERRIER = "Rat Terrier"
    RED_HEELER = "Red Heeler"
    REDBONE_COONHOUND = "Redbone Coonhound"
    RETRIEVER = "Retriever"
    RHODESIAN_RIDGEBACK = "Rhodesian Ridgeback"
    ROTTWEILER = "Rottweiler"
    SAINT_BERNARD = "Saint Bernard"
    SALUKI = "Saluki"
    SAMOYED = "Samoyed"
    SARPLANINAC = "Sarplaninac"
    SCHIPPERKE = "Schipperke"
    SCHNAUZER = "Schnauzer"
    SCOTTISH_DEERHOUND = "Scottish Deerhound"
    SCOTTISH_TERRIER = "Scottish Terrier"
    SEALYHAM_TERRIER = "Sealyham Terrier"
    SETTER = "Setter"
    SHAR_PEI = "Shar Pei"
    SHELTIE = "Sheltie"
    SHEPHERD = "Shepherd"
    SHETLAND_SHEEPDOG = "Shetland Sheepdog"
    SHIBA_INU = "Shiba Inu"
    SHIH_POO = "Shih Poo"
    SHIH_TZU = "Shih Tzu"
    SIBERIAN_HUSKY = "Siberian Husky"
    SILKY_TERRIER = "Silky Terrier"
    SKYE_TERRIER = "Skye Terrier"
    SLAUGHTER = "Slaughter"
    SLOUGHI = "Sloughi"
    SMALL_MIXED_BREED = "Small Mixed Breed"
    SMALL_SPANISH_HOUND = "Small Spanish Hound"
    SMOOTH_FOX_TERRIER = "Smooth Fox Terrier"
    SOFT_COATED_WHEATEN_TERRIER = "Soft-Coated Wheaten Terrier"
    SOUTH_RUSSIAN_OVTCHARKA = "South Russian Ovcharka"
    SPANIEL = "Spaniel"
    SPANISH_WATER_DOG = "Spanish Water Dog"
    SPITZ = "Spitz"
    SPRINGER_SPANIEL = "Springer Spaniel"
    STAFFORDSHIRE_BULL_TERRIER = "Staffordshire Bull Terrier"
    STANDARD_POODLE = "Standard Poodle"
    SUSSEX_SPANIEL = "Sussex Spaniel"
    SWEDISH_VALLHUND = "Swedish Vallhund"
    SWISS_HOUND = "Swiss Hound"
    SWISS_MOUNTAIN_DOG = "Swiss Mountain Dog"
    TERRIER = "Terrier"
    TEXAS_HEELER = "Texas Heeler"
    THAI_RIDGEBACK = "Thai Ridgeback"
    TIBETAN_MASTIFF = "Tibetan Mastiff"
    TIBETAN_SPANIEL = "Tibetan Spaniel"
    TIBETAN_TERRIER = "Tibetan Terrier"
    TOSA_INU = "Tosa Inu"
    TOY_FOX_TERRIER = "Toy Fox Terrier"
    TREEING_TENNESSEE_BRINDLE = "Treeing Tennessee Brindle"
    TREEING_WALKER_COONHOUND = "Treeing Walker Coonhound"
    VIZSLA = "Vizsla"
    WEIMARANER = "Weimaraner"
    WELSH_SPRINGER_SPANIEL = "Welsh Springer Spaniel"
    WELSH_TERRIER = "Welsh Terrier"
    WEST_HIGHLAND_WHITE_TERRIER = "West Highland White Terrier"
    WHEATEN_TERRIER = "Wheaten Terrier"
    WHIPPET = "Whippet"
    WHITE_SHEPHERD = "White Shepherd"
    WIENER_DOG = "Wiener Dog"
    WIRE_FOX_TERRIER = "Wire Fox Terrier"
    WIREHAIRED_POINTING_GRIFFON = "Wirehaired Pointing Griffon"
    WOLF_HYBRID = "Wolf Hybrid"
    XOLOITZCUINTLI = "Xoloitzcuintli"
    YELLOW_LABRADOR_RETRIEVER = "Yellow Labrador Retriever"
    YORKIPOO = "Yorkipoo"
    YORKSHIRE_TERRIER = "Yorkshire Terrier"
    MIXED_BREED = "Mixed Breed"

class DogCharacteristics(Enum):
    SMALL = 'Small'
    MEDIUM = 'Medium'
    LARGE = 'Large'
    GIANT = 'Giant'
    SHORT_HAIRED = 'Short-haired'
    LONG_HAIRED = 'Long-haired'
    DOUBLE_COATED = 'Double-coated'
    SINGLE_COATED = 'Single-coated'
    CURLY = 'Curly'
    STRAIGHT = 'Straight'
    WIRE_HAIRED = 'Wire-haired'
    SMOOTH = 'Smooth'
    BLACK = 'Black'
    WHITE = 'White'
    BROWN = 'Brown'
    GOLDEN = 'Golden'
    BRINDLE = 'Brindle'
    SPOTTED = 'Spotted'
    STRIPED = 'Striped'
    SOLID = 'Solid'
    PIED = 'Pied'
    BLUE_EYES = 'Blue eyes'
    BROWN_EYES = 'Brown eyes'
    HAZEL_EYES = 'Hazel eyes'
    GREEN_EYES = 'Green eyes'
    BLACK_EYES = 'Black eyes'

class PetTemperaments(Enum):
    FRIENDLY = 'Friendly'
    AFFECTIONATE = 'Affectionate'
    PLAYFUL = 'Playful'
    INDEPENDENT = 'Independent'
    LAID_BACK = 'Laid-back'
    GENTLE = 'Gentle'
    SHY = 'Shy'
    RESERVED = 'Reserved'
    VOCAL = 'Vocal'
    ACTIVE = 'Active'
    DOCILE = 'Docile'
    ADAPTABLE = 'Adaptable'
    ATTENTIVE = 'Attentive'
    EASY_GOING = 'Easy-going'
    STUBBORN = 'Stubborn'
    AGGRESSIVE = 'Aggressive'
    ANXIOUS = 'Anxious'
    BRAVE = 'Brave'
    CALM = 'Calm'
    CONFIDENT = 'Confident'
    COURAGEOUS = 'Courageous'
    CURIOUS = 'Curious'
    DEPENDABLE = 'Dependable'
    DEVOTED = 'Devoted'
    EAGER = 'Eager'
    ENERGETIC = 'Energetic'
    FAITHFUL = 'Faithful'
    FEARLESS = 'Fearless'
    FIERCE = 'Fierce'
    GREGARIOUS = 'Gregarious'
    HAPPY = 'Happy'
    HARDWORKING = 'Hardworking'
    HYPER = 'Hyper'
    INTELLIGENT = 'Intelligent'
    JOYFUL = 'Joyful'
    KIND = 'Kind'
    LIVELY = 'Lively'
    LOYAL = 'Loyal'
    MISCHIEVOUS = 'Mischievous'
    NOBLE = 'Noble'
    OBEDIENT = 'Obedient'
    PATIENT = 'Patient'
    PROTECTIVE = 'Protective'
    QUICK = 'Quick'
    QUIET = 'Quiet'
    RELAXED = 'Relaxed'
    RESPONSIBLE = 'Responsible'
    SENSITIVE = 'Sensitive'
    SENSIBLE = 'Sensible'
    SERIOUS = 'Serious'
    SINCERE = 'Sincere'
    SOCIAL = 'Social'
    STOIC = 'Stoic'
    STRONG = 'Strong'
    SWEET = 'Sweet'
    TENACIOUS = 'Tenacious'
    TERRITORIAL = 'Territorial'
    TOUGH = 'Tough'
    TRAINABLE = 'Trainable'
    TRUSTWORTHY = 'Trustworthy'
    VALIANT = 'Valiant'
    VERSATILE = 'Versatile'
    VIGILANT = 'Vigilant'
    ZEALOUS = 'Zealous'

class CatBreeds(Enum):
    ABYSSINIAN = "Abyssinian"
    AMERICAN_BOBTAIL = "American Bobtail"
    AMERICAN_CURL = "American Curl"
    AMERICAN_SHORTHAIR = "American Shorthair"
    AMERICAN_WIREHAIR = "American Wirehair"
    APPLEHEAD_SIAMESE = "Applehead Siamese"
    BALINESE = "Balinese"
    BENGAL = "Bengal"
    BIRMAN = "Birman"
    BOMBAY = "Bombay"
    BRITISH_SHORTHAIR = "British Shorthair"
    BURMESE = "Burmese"
    BURMILLA = "Burmilla"
    CALICO = "Calico"
    CANADIAN_HAIRLESS = "Canadian Hairless"
    CHARTREUX = "Chartreux"
    CHAUSIE = "Chausie"
    CHINCHILLA = "Chinchilla"
    CORNISH_REX = "Cornish Rex"
    CYMRIC = "Cymric"
    DEVON_REX = "Devon Rex"
    DILUTE_CALICO = "Dilute Calico"
    DILUTE_TORTOISESHELL = "Dilute Tortoiseshell"
    DOMESTIC_LONG_HAIR = "Domestic Long Hair"
    DOMESTIC_MEDIUM_HAIR = "Domestic Medium Hair"
    DOMESTIC_SHORT_HAIR = "Domestic Short Hair"
    EGYPTIAN_MAU = "Egyptian Mau"
    EXOTIC_SHORTHAIR = "Exotic Shorthair"
    EXTRA_TOES_CAT = "Extra-Toes Cat / Hemingway Polydactyl"
    HAVANA = "Havana"
    HIMALAYAN = "Himalayan"
    JAPANESE_BOBTAIL = "Japanese Bobtail"
    JAVANESE = "Javanese"
    KORAT = "Korat"
    LAPERM = "LaPerm"
    MAINE_COON = "Maine Coon"
    MANX = "Manx"
    MUNCHKIN = "Munchkin"
    NEBELUNG = "Nebelung"
    NORWEGIAN_FOREST_CAT = "Norwegian Forest Cat"
    OCICAT = "Ocicat"
    ORIENTAL_LONG_HAIR = "Oriental Long Hair"
    ORIENTAL_SHORT_HAIR = "Oriental Short Hair"
    ORIENTAL_TABBY = "Oriental Tabby"
    PERSIAN = "Persian"
    PIXIEBOB = "Pixiebob"
    RAGAMUFFIN = "Ragamuffin"
    RAGDOLL = "Ragdoll"
    RUSSIAN_BLUE = "Russian Blue"
    SCOTTISH_FOLD = "Scottish Fold"
    SELKIRK_REX = "Selkirk Rex"
    SIAMESE = "Siamese"
    SIBERIAN = "Siberian"
    SILVER = "Silver"
    SINGAPURA = "Singapura"
    SNOWSHOE = "Snowshoe"
    SOMALI = "Somali"
    SPHYNX = "Sphynx / Hairless Cat"
    TABBY = "Tabby"
    TIGER = "Tiger"
    TONKINESE = "Tonkinese"
    TORBIE = "Torbie"
    TORTOISESHELL = "Tortoiseshell"
    TOYGER = "Toyger"
    TURKISH_ANGORA = "Turkish Angora"
    TURKISH_VAN = "Turkish Van"
    TUXEDO = "Tuxedo"
    YORK_CHOCOLATE = "York Chocolate"

class CatCharacteristics(Enum):
    SMALL = 'Small'
    MEDIUM = 'Medium'
    LARGE = 'Large'
    SHORT_HAIRED = 'Short-haired'
    LONG_HAIRED = 'Long-haired'
    DOUBLE_COATED = 'Double-coated'
    SINGLE_COATED = 'Single-coated'
    CURLY = 'Curly'
    STRAIGHT = 'Straight'
    BLACK = 'Black'
    WHITE = 'White'
    GREY = 'Grey'
    BROWN = 'Brown'
    ORANGE = 'Orange'
    CALICO = 'Calico'
    TORTOISESHELL = 'Tortoiseshell'
    TABBY = 'Tabby'
    SIAMESE = 'Siamese'
    PERSIAN = 'Persian'
    BENGAL = 'Bengal'
    RAGDOLL = 'Ragdoll'
    SPHYNX = 'Sphynx'

class CatTemperaments(Enum):
    FRIENDLY = 'Friendly'
    AFFECTIONATE = 'Affectionate'
    PLAYFUL = 'Playful'
    INDEPENDENT = 'Independent'
    LAID_BACK = 'Laid-back'
    CURIOUS = 'Curious'
    GENTLE = 'Gentle'
    SHY = 'Shy'
    RESERVED = 'Reserved'
    VOCAL = 'Vocal'
    ACTIVE = 'Active'
    DOCILE = 'Docile'
    ADAPTABLE = 'Adaptable'
    ATTENTIVE = 'Attentive'
    EASY_GOING = 'Easy-going'
    PET_FRIENDLY = 'Pet Friendly'